/* ═══════════════════════════════════════════════════════════
   ExpiryTrack — lang.js  (v2 — Tam Türkçe Sözlük)
═══════════════════════════════════════════════════════════ */
const TR = {
  /* ── Uygulama ── */
  appName:            'ExpiryTrack',
  appTagline:         'Akıllı Son Kullanma Takip Sistemi',
  save:               'Kaydet',
  cancel:             'İptal',
  delete:             'Sil',
  edit:               'Düzenle',
  add:                'Ekle',
  clear:              'Temizle',
  seeAll:             'Tümünü Gör',
  viewAll:            'Tümünü Gör',
  required:           '*',
  optional:           '(isteğe bağlı)',
  noData:             '—',
  actions:            'İşlemler',
  close:              'Kapat',
  yes:                'Evet',
  no:                 'Hayır',
  search:             'Ara...',
  loading:            'Yükleniyor...',
  themeToggleTitle:   'Tema Değiştir',
  logoutTitle:        'Çıkış Yap',

  /* ── Roller ── */
  roleAdmin:          'Süper Admin',
  roleUser:           'Mağaza Kullanıcısı',

  /* ── Giriş ── */
  loginUsername:      'Kullanıcı Adı',
  loginPassword:      'Şifre',
  loginUserPh:        'Kullanıcı adınızı girin',
  loginPassPh:        'Şifrenizi girin',
  loginBtn:           'Giriş Yap',
  loginDemoHint:      'Demo Hesaplar:',
  loginErrUsername:   'Kullanıcı adı zorunludur',
  loginErrPassword:   'Şifre zorunludur',
  loginErrInvalid:    'Kullanıcı adı veya şifre hatalı',
  loginFailed:        'Giriş başarısız. Bilgilerinizi kontrol edin.',
  logoutSuccess:      'Başarıyla çıkış yapıldı.',
  noStoreAssigned:    'Hesabınıza henüz mağaza atanmamış. Lütfen yöneticiyle iletişime geçin.',

  /* ── Sidebar ── */
  navDashboard:       'Gösterge Paneli',
  navAddProduct:      'Ürün Ekle',
  navProductList:     'Ürün Listesi',
  navCategories:      'Kategoriler',
  navStores:          'Mağazalar',
  navBrands:          'Markalar',
  navUsers:           'Kullanıcılar',
  navSettings:        'Ayarlar',
  navAdminOnly:       'Yalnızca Admin',

  /* ── Sayfa Başlıkları ── */
  pageDashboard:      'Gösterge Paneli',
  pageAddProduct:     'Ürün Ekle',
  pageProductList:    'Ürün Listesi',
  pageCategories:     'Kategoriler',
  pageStores:         'Mağazalar',
  pageBrands:         'Markalar',
  pageUsers:          'Kullanıcılar',
  pageSettings:       'Sistem Ayarları',
  pageCategoryDetail: 'Kategori Detayı',
  pageBrandDetail:    'Marka Detayı',

  /* ── Dashboard ── */
  dashOverview:       'Genel Bakış',
  dashSubtitle:       'Ürünlerinizin son kullanma durumunu anlık takip edin',
  statStores:         'Toplam Mağaza',
  statCategories:     'Kategoriler',
  statBrands:         'Toplam Marka',
  statTotal:          'Toplam Ürün',
  statExpired:        'Süresi Dolmuş',
  statSoon7:          '7 Günde Dolacak',
  statSoon30:         '30 Günde Dolacak',
  criticalTitle:      'Kritik Ürünler',
  allGood:            'Tüm ürünler iyi durumda!',
  alertExpired:       (n) => `${n} ürünün süresi dolmuş`,
  alertSoon7:         (n) => `${n} ürün 7 gün içinde dolacak`,
  warningSection:     '7 Gün İçinde Dolacak Ürünler',

  /* ── Durum Etiketleri ── */
  statusExpired:      'Süresi Doldu',
  statusToday:        'Bugün!',
  statusTomorrow:     'Yarın!',
  statusDaysLeft:     (n) => `${n} gün kaldı`,

  /* ── Tablo Başlıkları ── */
  colProduct:         'Ürün',
  colCategory:        'Kategori',
  colBrand:           'Marka',
  colStore:           'Mağaza',
  colBarcode:         'Barkod',
  colQty:             'Adet',
  colExpiry:          'Son Kullanma',
  colStatus:          'Durum',
  colAdded:           'Eklenme',
  colActions:         'İşlemler',
  colTotalQty:        'Toplam Adet',
  colProducts:        'Ürün Sayısı',
  colExpiring:        'Dolmak Üzere',

  /* ── Ürün Ekle ── */
  addProductTitle:    'Ürün Ekle',
  addProductSub:      'Yeni ürünü sisteme kaydedin',
  fieldName:          'Ürün Adı',
  fieldNamePh:        'örn. Çikolatalı Gofret',
  fieldStore:         'Mağaza',
  fieldStorePh:       'Mağaza seçin',
  fieldCategory:      'Kategori',
  fieldCategoryPh:    'Kategori seçin',
  fieldBrand:         'Marka',
  fieldBrandPh:       'Marka seçin',
  fieldBarcode:       'Barkod',
  fieldBarcodePh:     'örn. 8690123456789',
  fieldQty:           'Adet',
  fieldQtyPh:         'örn. 24',
  fieldExpiry:        'Son Kullanma Tarihi',
  addProductBtn:      'Ürün Ekle',
  addProductSuccess:  (name) => `"${name}" başarıyla eklendi!`,
  addSuccessMsg:      'Ürün başarıyla eklendi!',
  errNameRequired:    'Ürün adı zorunludur',
  errStoreRequired:   'Lütfen bir mağaza seçin',
  errCatRequired:     'Lütfen bir kategori seçin',
  errBrandRequired:   'Lütfen bir marka seçin',
  errQtyRequired:     'Geçerli bir adet girin',
  errExpiryRequired:  'Son kullanma tarihi zorunludur',
  errFieldsRequired:  'Lütfen zorunlu alanları doldurun.',

  /* ── Ürün Listesi ── */
  productListTitle:   'Ürün Listesi',
  productListSub:     'Tüm ürünler — mağaza, kategori ve marka bilgisiyle',
  searchPlaceholder:  'Ürün, barkod, marka ara...',
  filterAllCats:      'Tüm Kategoriler',
  filterAllStores:    'Tüm Mağazalar',
  filterAllBrands:    'Tüm Markalar',
  sortExpiryAsc:      'Son Kullanma: Yakın',
  sortExpiryDesc:     'Son Kullanma: Uzak',
  sortNameAsc:        'Ad: A-Z',
  sortNameDesc:       'Ad: Z-A',
  noProductsFound:    'Ürün bulunamadı.',
  addFirstProduct:    'İlk Ürünü Ekle',
  editProductTitle:   'Ürünü Düzenle',
  editSuccess:        (name) => `"${name}" başarıyla güncellendi!`,
  deleteProductTitle: 'Ürünü Sil',
  deleteConfirmText:  (name) => `<strong>${name}</strong> ürününü silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.`,
  deleteSuccess:      (name) => `"${name}" silindi.`,
  editTitle:          'Düzenle',
  deleteTitle:        'Sil',

  /* ── Kategoriler (SABİT) ── */
  categoriesTitle:    'Kategoriler',
  categoriesSub:      'Ürün kategorileri ve marka yönetimi',
  catProducts:        (n) => `${n} ürün`,
  catBrands:          (n) => `${n} marka`,
  catViewBrands:      'Markaları Gör',
  catEmpty:           'Kategori bulunamadı.',
  FIXED_CATEGORIES: [
    { id: 'abur-cubur',      name: 'Abur Cubur',       icon: 'fa-cookie-bite',    color: '#f59e0b' },
    { id: 'acik-sarkuteri',  name: 'Açık Şarküteri',   icon: 'fa-cheese',         color: '#ef4444' },
    { id: 'kapali-sarkuteri',name: 'Kapalı Şarküteri', icon: 'fa-box',            color: '#8b5cf6' },
    { id: 'kasap',           name: 'Kasap',             icon: 'fa-drumstick-bite', color: '#dc2626' },
    { id: 'tavuk',           name: 'Tavuk',             icon: 'fa-egg',            color: '#f97316' },
    { id: 'icecek',          name: 'İçecek',            icon: 'fa-bottle-water',   color: '#0ea5e9' },
  ],

  /* ── Markalar ── */
  brandsTitle:        'Markalar',
  brandsSub:          'Kategori bazlı marka yönetimi',
  brandName:          'Marka Adı',
  brandNamePh:        'örn. Eti, Ülker, Nestle',
  brandLogo:          'Marka Logosu',
  brandCategory:      'Kategori',
  addBrandTitle:      'Marka Ekle',
  editBrandTitle:     'Markayı Düzenle',
  deleteBrandTitle:   'Markayı Sil',
  deleteBrandConfirm: (name) => `<strong>${name}</strong> markasını silmek istediğinizden emin misiniz?`,
  brandAddSuccess:    (name) => `"${name}" markası eklendi!`,
  brandEditSuccess:   (name) => `"${name}" markası güncellendi!`,
  brandDeleteSuccess: (name) => `"${name}" markası silindi.`,
  brandDeleteInUse:   (name) => `"${name}" silinemez — bu markaya ait ürün var.`,
  brandNameRequired:  'Marka adı zorunludur',
  brandCatRequired:   'Kategori seçimi zorunludur',
  noBrandsFound:      'Henüz marka eklenmemiş.',
  addFirstBrand:      'İlk Markayı Ekle',

  /* ── Mağazalar ── */
  storesTitle:        'Mağazalar',
  storesSub:          'Sistem genelindeki mağazaları yönetin',
  storeName:          'Mağaza Adı',
  storeNamePh:        'örn. Merkez Mağaza',
  storeDesc:          'Açıklama',
  storeDescPh:        'Mağaza hakkında kısa açıklama',
  storeLogo:          'Mağaza Logosu',
  addStoreTitle:      'Mağaza Ekle',
  editStoreTitle:     'Mağazayı Düzenle',
  deleteStoreTitle:   'Mağazayı Sil',
  deleteStoreConfirm: (name) => `<strong>${name}</strong> mağazasını silmek istediğinizden emin misiniz? Bu mağazaya ait tüm ürünler de silinecektir.`,
  storeAddSuccess:    (name) => `"${name}" mağazası eklendi!`,
  storeEditSuccess:   (name) => `"${name}" mağazası güncellendi!`,
  storeDeleteSuccess: (name) => `"${name}" mağazası silindi.`,
  storeNameRequired:  'Mağaza adı zorunludur',
  noStoresFound:      'Henüz mağaza eklenmemiş.',
  storeProducts:      (n) => `${n} ürün`,
  storeExpiring:      (n) => `${n} dolmak üzere`,
  storeExpired:       (n) => `${n} süresi dolmuş`,

  /* ── Kullanıcılar ── */
  usersTitle:         'Kullanıcılar',
  usersSub:           'Sistem kullanıcılarını ve mağaza atamalarını yönetin',
  userName:           'Kullanıcı Adı',
  userNamePh:         'örn. kullanici1',
  userPass:           'Şifre',
  userPassPh:         'Şifre girin',
  userRole:           'Rol',
  userStore:          'Atanan Mağaza',
  userStorePh:        'Mağaza seçin',
  addUserTitle:       'Kullanıcı Ekle',
  editUserTitle:      'Kullanıcıyı Düzenle',
  deleteUserTitle:    'Kullanıcıyı Sil',
  deleteUserConfirm:  (name) => `<strong>${name}</strong> kullanıcısını silmek istediğinizden emin misiniz?`,
  userAddSuccess:     (name) => `"${name}" kullanıcısı eklendi!`,
  userEditSuccess:    (name) => `"${name}" kullanıcısı güncellendi!`,
  userDeleteSuccess:  (name) => `"${name}" kullanıcısı silindi.`,
  userDeleteSelf:     'Kendi hesabınızı silemezsiniz.',
  userNameRequired:   'Kullanıcı adı zorunludur',
  userPassRequired:   'Şifre zorunludur',
  userStoreRequired:  'Kullanıcılar için mağaza seçimi zorunludur',
  userNameExists:     'Bu kullanıcı adı zaten kullanılıyor',
  noUsersFound:       'Henüz kullanıcı eklenmemiş.',

  /* ── Ayarlar (ADMIN) ── */
  settingsTitle:      'Sistem Ayarları',
  settingsSub:        'Uygulama genelindeki sistem ayarlarını yönetin',
  settingsAppName:    'Uygulama Adı',
  settingsAppNamePh:  'Uygulama adını girin',
  settingsTagline:    'Alt Başlık',
  settingsTaglinePh:  'örn. Akıllı Son Kullanma Takip Sistemi',
  settingsLogo:       'Uygulama Logosu (URL)',
  settingsLogoPh:     'https://... veya data:image/...',
  settingsSaveSuccess:'Ayarlar başarıyla kaydedildi!',
  settingsAdminPass:  'Admin Şifresi Değiştir',
  settingsNewPass:    'Yeni Şifre',
  settingsNewPassPh:  'Yeni şifre girin',
  settingsPassSuccess:'Şifre başarıyla güncellendi!',
  settingsPassErr:    'Yeni şifre zorunludur',
  accessDenied:       'Bu sayfaya erişim yetkiniz yok.',
};

function t(key, ...args) {
  const val = TR[key];
  if (val === undefined) { console.warn(`[i18n] Eksik: "${key}"`); return key; }
  if (typeof val === 'function') return val(...args);
  return val;
}
